/* eslint-disable no-useless-escape */
const Ziggy = {
    url: 'http:\/\/dev-staging-novatix.id:8000',
    port: 8000,
    defaults: {},
    routes: {
        'debugbar.openhandler': {
            uri: '_debugbar\/open',
            methods: ['GET', 'HEAD'],
        },
        'debugbar.clockwork': {
            uri: '_debugbar\/clockwork\/{id}',
            methods: ['GET', 'HEAD'],
            parameters: ['id'],
        },
        'debugbar.assets.css': {
            uri: '_debugbar\/assets\/stylesheets',
            methods: ['GET', 'HEAD'],
        },
        'debugbar.assets.js': {
            uri: '_debugbar\/assets\/javascript',
            methods: ['GET', 'HEAD'],
        },
        'debugbar.cache.delete': {
            uri: '_debugbar\/cache\/{key}\/{tags?}',
            methods: ['DELETE'],
            parameters: ['key', 'tags'],
        },
        'debugbar.queries.explain': {
            uri: '_debugbar\/queries\/explain',
            methods: ['POST'],
        },
        'filament.exports.download': {
            uri: 'filament\/exports\/{export}\/download',
            methods: ['GET', 'HEAD'],
            parameters: ['export'],
            bindings: { export: 'id' },
        },
        'filament.imports.failed-rows.download': {
            uri: 'filament\/imports\/{import}\/failed-rows\/download',
            methods: ['GET', 'HEAD'],
            parameters: ['import'],
            bindings: { import: 'id' },
        },
        'filament.admin.auth.logout': {
            uri: 'admin\/logout',
            methods: ['POST'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.admin.pages.dashboard': {
            uri: 'admin\/{tenant}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.events.index': {
            uri: 'admin\/{tenant}\/events',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.events.create': {
            uri: 'admin\/{tenant}\/events\/create',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.events.edit': {
            uri: 'admin\/{tenant}\/events\/{record}\/edit',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant', 'record'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.events.view': {
            uri: 'admin\/{tenant}\/events\/{record}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant', 'record'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.orders.index': {
            uri: 'admin\/{tenant}\/orders',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.orders.create': {
            uri: 'admin\/{tenant}\/orders\/create',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.orders.edit': {
            uri: 'admin\/{tenant}\/orders\/{record}\/edit',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant', 'record'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.orders.view': {
            uri: 'admin\/{tenant}\/orders\/{record}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant', 'record'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.tickets.index': {
            uri: 'admin\/{tenant}\/tickets',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.tickets.view': {
            uri: 'admin\/{tenant}\/tickets\/{record}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant', 'record'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.venues.index': {
            uri: 'admin\/{tenant}\/venues',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.venues.create': {
            uri: 'admin\/{tenant}\/venues\/create',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.venues.edit': {
            uri: 'admin\/{tenant}\/venues\/{record}\/edit',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant', 'record'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.resources.venues.view': {
            uri: 'admin\/{tenant}\/venues\/{record}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['tenant', 'record'],
            bindings: { tenant: 'code' },
        },
        'filament.admin.tenant': {
            uri: 'admin',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.auth.logout': {
            uri: 'novatix-admin\/logout',
            methods: ['POST'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.pages.dashboard': {
            uri: 'novatix-admin',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.resources.events.index': {
            uri: 'novatix-admin\/events',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.resources.events.create': {
            uri: 'novatix-admin\/events\/create',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.resources.events.edit': {
            uri: 'novatix-admin\/events\/{record}\/edit',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['record'],
        },
        'filament.novatix-admin.resources.events.view': {
            uri: 'novatix-admin\/events\/{record}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['record'],
        },
        'filament.novatix-admin.resources.orders.index': {
            uri: 'novatix-admin\/orders',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.resources.orders.create': {
            uri: 'novatix-admin\/orders\/create',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.resources.orders.edit': {
            uri: 'novatix-admin\/orders\/{record}\/edit',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['record'],
        },
        'filament.novatix-admin.resources.orders.view': {
            uri: 'novatix-admin\/orders\/{record}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['record'],
        },
        'filament.novatix-admin.resources.teams.index': {
            uri: 'novatix-admin\/teams',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.resources.teams.create': {
            uri: 'novatix-admin\/teams\/create',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.resources.teams.edit': {
            uri: 'novatix-admin\/teams\/{record}\/edit',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['record'],
        },
        'filament.novatix-admin.resources.teams.view': {
            uri: 'novatix-admin\/teams\/{record}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['record'],
        },
        'filament.novatix-admin.resources.tickets.index': {
            uri: 'novatix-admin\/tickets',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.resources.tickets.view': {
            uri: 'novatix-admin\/tickets\/{record}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['record'],
        },
        'filament.novatix-admin.resources.users.index': {
            uri: 'novatix-admin\/users',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.resources.users.create': {
            uri: 'novatix-admin\/users\/create',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.resources.users.edit': {
            uri: 'novatix-admin\/users\/{record}\/edit',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['record'],
        },
        'filament.novatix-admin.resources.users.view': {
            uri: 'novatix-admin\/users\/{record}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['record'],
        },
        'filament.novatix-admin.resources.venues.index': {
            uri: 'novatix-admin\/venues',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.resources.venues.create': {
            uri: 'novatix-admin\/venues\/create',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'filament.novatix-admin.resources.venues.edit': {
            uri: 'novatix-admin\/venues\/{record}\/edit',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['record'],
        },
        'filament.novatix-admin.resources.venues.view': {
            uri: 'novatix-admin\/venues\/{record}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['record'],
        },
        'sanctum.csrf-cookie': {
            uri: 'sanctum\/csrf-cookie',
            methods: ['GET', 'HEAD'],
        },
        'livewire.update': { uri: 'livewire\/update', methods: ['POST'] },
        'livewire.upload-file': {
            uri: 'livewire\/upload-file',
            methods: ['POST'],
        },
        'livewire.preview-file': {
            uri: 'livewire\/preview-file\/{filename}',
            methods: ['GET', 'HEAD'],
            parameters: ['filename'],
        },
        login: {
            uri: 'login',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'auth.google': {
            uri: 'auth\/google',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'auth.google-authentication': {
            uri: 'auth\/google-callback',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        home: {
            uri: '\/',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        privacy_policy: {
            uri: 'privacy-policy',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        terms_conditions: {
            uri: 'terms-conditions',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'seats.index': {
            uri: 'seats',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'seats.grid-edit': {
            uri: 'seats\/grid-edit',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'seats.edit': {
            uri: 'seats\/edit',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
        },
        'seats.update-layout': {
            uri: 'seats\/update-layout',
            methods: ['POST'],
            domain: 'dev-staging-novatix.id',
        },
        'seats.update': {
            uri: 'seats\/update',
            methods: ['POST'],
            domain: 'dev-staging-novatix.id',
        },
        'seats.update-event-seats': {
            uri: 'seats\/update-event-seats',
            methods: ['POST'],
            domain: 'dev-staging-novatix.id',
        },
        'seats.save-grid-layout': {
            uri: 'seats\/save-grid-layout',
            methods: ['POST'],
            domain: 'dev-staging-novatix.id',
        },
        'venues.export': {
            uri: 'venues\/{venue}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['venue'],
        },
        'orders.export': {
            uri: 'orders\/download\/{id?}',
            methods: ['GET', 'HEAD'],
            domain: 'dev-staging-novatix.id',
            parameters: ['id'],
        },
        'client.formRegistration': {
            uri: 'formRegistration',
            methods: ['POST'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'client.login': {
            uri: 'login',
            methods: ['GET', 'HEAD'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'client.privateLogin': {
            uri: 'privateLogin',
            methods: ['GET', 'HEAD'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'client-auth.google': {
            uri: 'auth\/google',
            methods: ['GET', 'HEAD'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'client.verify-event-password': {
            uri: 'verify-event-password',
            methods: ['POST'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'client.home': {
            uri: '\/',
            methods: ['GET', 'HEAD'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'client.privacy_policy': {
            uri: 'privacy-policy',
            methods: ['GET', 'HEAD'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'client.terms_conditions': {
            uri: 'terms-conditions',
            methods: ['GET', 'HEAD'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'client.my_tickets': {
            uri: 'my_tickets',
            methods: ['GET', 'HEAD'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'client.client.scan': {
            uri: 'events\/{event_slug}\/scan',
            methods: ['GET', 'HEAD'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client', 'event_slug'],
        },
        'client.client.scan.store': {
            uri: 'events\/{event_slug}\/scan',
            methods: ['POST'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client', 'event_slug'],
        },
        'api.tickets.download': {
            uri: 'api\/tickets\/download',
            methods: ['GET', 'HEAD'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'payment.pending': {
            uri: 'api\/payment\/pending',
            methods: ['GET', 'HEAD'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'payment.cancel': {
            uri: 'api\/payment\/cancel',
            methods: ['POST'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'payment.get-client': {
            uri: 'api\/payment\/get-client',
            methods: ['GET', 'HEAD'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'payment.charge': {
            uri: 'api\/payment\/charge',
            methods: ['POST'],
            domain: '{client}.dev-staging-novatix.id',
            parameters: ['client'],
        },
        'post.login': { uri: 'login', methods: ['POST'] },
        logout: { uri: 'logout', methods: ['POST'] },
        'payment.midtransCallback': {
            uri: 'api\/payment\/midtransCallback',
            methods: ['POST'],
        },
        'payment.midtransReturn': {
            uri: 'api\/payment\/midtransReturn',
            methods: ['GET', 'HEAD'],
        },
        'payment.faspayCallback': {
            uri: 'api\/payment\/faspayCallback',
            methods: ['POST'],
        },
        'payment.faspayReturn': {
            uri: 'api\/payment\/faspayReturn',
            methods: ['GET', 'HEAD'],
        },
        'payment.tripayCallback': {
            uri: 'api\/payment\/tripayCallback',
            methods: ['POST'],
        },
        'payment.tripayReturn': {
            uri: 'api\/payment\/tripayReturn',
            methods: ['GET', 'HEAD'],
        },
        'storage.local': {
            uri: 'storage\/{path}',
            methods: ['GET', 'HEAD'],
            wheres: { path: '.*' },
            parameters: ['path'],
        },
    },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
