name: ArachnoVa VPS Actions

on:
  push:
    branches:
      - main

jobs:
  vps_sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/av_rsa
          chmod 600 ~/.ssh/av_rsa
          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: Ensure Repository Exists on VPS
        run: |
          ssh -i ~/.ssh/av_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            if [ ! -d '~/novatix/.git' ]; then
              echo 'Repository not found. Cloning...'
              rm -rf ~/novatix  # Remove existing folder if it's not a git repo
              git clone git@github.com:ArachnoVa-id/novatix.git ~/novatix
            else
              echo 'Repository exists.'
            fi
          "

      - name: Pull Latest Changes on VPS
        run: |
          ssh -i ~/.ssh/av_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ~/novatix && git pull origin main"
